version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  ap:
    depends_on:
      - db
    container_name: fastapi
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: ${PORT}
      PYTHONBUFFERED: 1
      WEB_CONCURRENCY: 4
      WORKERS_PER_CORE: 2
      GUNICORN_CMD_ARGS: "--preload --timeout 30 --keep-alive 2 --log-level info"
    ports:
      - '${PORT}:${PORT}'
    expose:
      - '${PORT}'
# Names our volume
volumes:
  my-db: