version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  ap:
    depends_on:
      - db
    container_name: fastapi
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: ${PORT}
    ports:
      - '8000:8000'
    expose:
      - '8000'
# Names our volume
volumes:
  my-db: