"""initial tables

Revision ID: 106413f46f4c
Revises: 
Create Date: 2023-05-08 20:55:19.294265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106413f46f4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
