"""file table

Revision ID: 3e1d923befa1
Revises: 07c8d8df4a29
Create Date: 2023-04-24 09:44:15.568647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e1d923befa1'
down_revision = '07c8d8df4a29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file', sa.Column('s3_key_name', sa.String(length=100), nullable=False))
    op.drop_column('user_file', 'key_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file', sa.Column('key_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('user_file', 's3_key_name')
    # ### end Alembic commands ###
